### ISSUE TITLE
Transferring UserSessionNotes from AuthSession to UserSession while Login failing

### ISSUE THREAD

**Issue by tobimuell** [opdt/keycloak-cassandra-extension#5]
I try to set a custom UserSessionNote in a custom Authentication-Execution-Step with

`
AuthenticationSessionModel.getUserSessionNotes().setNote("key","value");
`

This UserSessionNote I would like to pick up again in a TokenMapper and write it accordingly into the JWT with follow code

` UserSessionModel.getNote("key")`

Unfortunately, the value in the TokenManager is always empty.

Note I did a debug session where I found out that the Notes in `UserSessionRepository.insertOrUpdate` seem to be always overwritten. If after the call of the TokenManager still further calls come thus the Notes set by me are overwritten.

**Comment by opdt** [comment]
First analysis shows that AuthenticatedClientSessionModels sometimes have a stale reference to their corresponding user session. Since the user session is the aggregate root and is saved whenever the auth client session is updated, this leads to overriding the user session with old data.
